from graph.state import AgentState
from graph.nodes.clean_agent import load_dataframe
import os

# -------------------------------------------
from dotenv import load_dotenv
load_dotenv()
from langchain_groq import ChatGroq

# LLM ---
model = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.3)

def llm_call(promt):
    response = model.invoke(promt)
    return response.content

# -------------------------------------------


#report to docs -- 
from docx import Document
from docx.shared import Inches , Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import re
# -------

# FUNXN --- 
def build_dataset_overview(df):
    rows , columns = df.shape
    numeric_col = df.select_dtypes(include='number').columns.tolist()
    categorical_col = df.select_dtypes(include='object').columns.tolist()

    return {
        "row_count":rows,
        "column_count":columns,
        "numeric_columns": numeric_col,
        "categorical_columns": categorical_col,
        "schema": {col : str(dtype) for col , dtype in df.dtypes.items()}
    }

    # not resuing df_schema bec -- df_schema only tells us dtype strings ("int64", "object")



def build_cleaning_summary(cleaning_issues,cleaning_decisions):
    summary = []

    for issue in cleaning_issues:
        if issue["issue_type"] not in ("missing_values", "duplicate_rows"):
            continue
        action = cleaning_decisions.get(issue['id'],"skip")
        if action == "skip":
            continue

        summary.append({
            "column":issue['column'],
            "issue_type":issue['issue_type'],
            "description":issue['description'],
            "action_taken":action
        })
    return summary


def build_annomalies_detection(cleaning_issues,cleaning_decisions):
    anomalies = []
    for issue in cleaning_issues:
        if issue["issue_type"] in ("invalid_values", "type_mismatch", "categorical_inconsistency"):
            action = cleaning_decisions.get(issue['id'],"not_addressed")

            anomalies.append({
                "column":issue['column'],
                "description":issue['description'],
                "status":action
            })

    return anomalies


def generate_key_findings(eda_results):
    prompt = f"""You are a data analyst writing a formal EDA report.
        Given these statistics, write 3-4 findings in this exact format:
        **Insight:** [observation]
        **Interpretation:** [what it likely means]

        Only reference the numbers below. Do not invent numbers.

        Summary stats: {eda_results['summary_stats']}
        Correlations: {eda_results['correlations']}
        Value counts: {eda_results['value_counts']}
        """

    return llm_call(prompt)


def generate_plain_summary(key_findings_text):
    prompt = f"""Explain the following data analysis findings in plain, everyday language
        for someone with no technical or statistics background. Avoid jargon like "correlation"
        or "distribution" — describe what's actually happening in the data and why it matters,
        in 4-5 sentences.

        Findings:
        {key_findings_text}
        """

    return llm_call(prompt)


def add_watermark_footer(doc):
    section = doc.sections[0]
    footer = section.footer
    p = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    p.text = "Generated by TazzaCode AI"
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in p.runs:
        run.font.size = Pt(8)
        run.font.italic = True  


# Report to DOCX-- 

def add_formatted_paragraph(doc, text):
    parts = re.split(r'(\*\*.*?\*\*)', text)
    p = doc.add_paragraph()
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            p.add_run(part[2:-2]).bold = True
        else:
            p.add_run(part)


def assemble_report(report_sections,output_path):
    doc = Document()

    doc.add_heading("Exploratory Data Analysis Report",level=0)

    #dataset overview -
    doc.add_heading("1. Dataset Overview", level=1)
    overview = report_sections["overview"]
    doc.add_paragraph(f"This dataset contains {overview['row_count']} rows and {overview['column_count']} columns.")
    doc.add_paragraph(f"Numeric columns: {', '.join(overview['numeric_columns'])}")
    doc.add_paragraph(f"Categorical columns: {', '.join(overview['categorical_columns'])}")

    #cleaning summary -
    doc.add_heading("2. Data Cleaning Summary", level=1)
    if report_sections["cleaning_summary"]:
        for item in report_sections["cleaning_summary"]:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(f"{item['column']}: ").bold = True
            p.add_run(f"{item['description']} — action taken: {item['action_taken']}")
    else:
        doc.add_paragraph("No cleaning actions were applied to this dataset.")

    #anomalies
    doc.add_heading("3. Anomalies & Data Quality Notes", level=1)
    if report_sections["anomalies"]:
        for item in report_sections["anomalies"]:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(f"{item['column']}: ").bold = True
            p.add_run(f"{item['description']} — status: {item['status']}")
    else:
        doc.add_paragraph("No anomalies were detected.")

    #Key Findings --
    doc.add_heading("4. Key Findings", level=1)
    for block in report_sections["key_findings"].split("\n\n"):
        if block.strip():
            add_formatted_paragraph(doc, block.strip())

    #charts ---
    if report_sections["chart_paths"]:
        doc.add_heading("5. Visualizations", level=1)
        for chart_path in report_sections["chart_paths"]:
            doc.add_picture(chart_path, width=Inches(6))
            doc.add_paragraph()  # spacing after image


    #plain-language summary ---
    doc.add_heading("6. Summary in Plain Language", level=1)
    doc.add_paragraph(report_sections["plain_summary"])

    # footer-- 
    
    add_watermark_footer(doc)

    doc.save(output_path)
    return output_path





        
# NODEEEEEEEEEEE

def report_generation_node(state:AgentState):
    file_path = state.get("cleaned_file_path") or state["file_path"]
    df = load_dataframe(file_path)

    overview = build_dataset_overview(df)
    cleaning_summary = build_cleaning_summary(state['cleaning_issues'],state['cleaning_decisions'])
    anomalies = build_annomalies_detection(state['cleaning_issues'],state['cleaning_decisions'])
    key_findings = generate_key_findings(state['eda_results'])
    plain_summary = generate_plain_summary(key_findings)

    report_sections = {
            "overview": overview,
            "cleaning_summary": cleaning_summary,
            "anomalies": anomalies,
            "key_findings": key_findings,
            "plain_summary": plain_summary,
            "chart_paths": state["eda_results"]["chart_paths"]
        }

    output_path = os.path.splitext(file_path)[0] + "_report.docx"
    assemble_report(report_sections,output_path)

    return {
        "report_file_path": output_path,
        "report_sections":  report_sections,
        "report_generated": True
    }



